// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WanderDragon.Data;

namespace WanderDragon.Data.Migrations
{
    [DbContext(typeof(WanderDragonContext))]
    partial class WanderDragonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WanderDragon.Data.TravelLog", b =>
                {
                    b.Property<int>("TravelLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<int>("ProfileId");

                    b.HasKey("TravelLogId");

                    b.HasIndex("ProfileId");

                    b.ToTable("TravelLog");
                });

            modelBuilder.Entity("WanderDragon.Models.Dragon", b =>
                {
                    b.Property<int>("DragonId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<int>("ChallengesWon");

                    b.Property<int>("DragonSpriteId");

                    b.Property<string>("Hometown");

                    b.Property<decimal>("KmRadius");

                    b.Property<decimal>("KmTravelled");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<int>("ProfileId");

                    b.Property<int>("TripsTaken");

                    b.Property<int>("XP");

                    b.HasKey("DragonId");

                    b.HasIndex("DragonSpriteId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Dragon");
                });

            modelBuilder.Entity("WanderDragon.Models.DragonSprite", b =>
                {
                    b.Property<int>("DragonSpriteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image1");

                    b.Property<string>("Image2");

                    b.Property<string>("Image3");

                    b.HasKey("DragonSpriteId");

                    b.ToTable("DragonSprite");
                });

            modelBuilder.Entity("WanderDragon.Models.ItemLog", b =>
                {
                    b.Property<int>("ItemLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Alexandrite");

                    b.Property<int>("Amethyst");

                    b.Property<int>("AnimalMask");

                    b.Property<int>("Aquamarine");

                    b.Property<int>("BeadedNecklace");

                    b.Property<int>("Bloodstone");

                    b.Property<int>("Boomarang");

                    b.Property<int>("Cherryblossom");

                    b.Property<int>("Cholla");

                    b.Property<int>("Croissant");

                    b.Property<int>("Garnet");

                    b.Property<int>("Hamburger");

                    b.Property<int>("HockeyPuck");

                    b.Property<int>("Jade");

                    b.Property<int>("KoalaDoll");

                    b.Property<int>("MapleLeaf");

                    b.Property<int>("MatryoshkaDoll");

                    b.Property<int>("Moonstone");

                    b.Property<int>("Noodlebowl");

                    b.Property<int>("Opal");

                    b.Property<int>("ParrotFeather");

                    b.Property<int>("Pearl");

                    b.Property<int>("Pierogi");

                    b.Property<int>("PinaColada");

                    b.Property<int>("Pineapple");

                    b.Property<int>("Plumeria");

                    b.Property<int>("ProfileId");

                    b.Property<int>("Sapphire");

                    b.Property<int>("TeaBag");

                    b.Property<int>("TigersEye");

                    b.Property<int>("Topaz");

                    b.Property<int>("Turquoise");

                    b.HasKey("ItemLogId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ItemLog");
                });

            modelBuilder.Entity("WanderDragon.Models.ItemSprite", b =>
                {
                    b.Property<int>("ItemSpriteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("ItemName");

                    b.HasKey("ItemSpriteId");

                    b.ToTable("ItemSprite");
                });

            modelBuilder.Entity("WanderDragon.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutMe");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Image");

                    b.Property<DateTime>("JoinDate");

                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("ProfileId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("WanderDragon.Data.TravelLog", b =>
                {
                    b.HasOne("WanderDragon.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WanderDragon.Models.Dragon", b =>
                {
                    b.HasOne("WanderDragon.Models.DragonSprite", "DragonSprite")
                        .WithMany()
                        .HasForeignKey("DragonSpriteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WanderDragon.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WanderDragon.Models.ItemLog", b =>
                {
                    b.HasOne("WanderDragon.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
